version: '2.2'

catalog:

  name: nextcloud nginx proxy lets encrypt
  version: 0.0.1
  description: Nextcloud - Enterprise File Sync and Share
  questions:
    - variable: MYSQL_DATABASE
      default: nextcloud
      label: MySQL Database
      required: true
      type: string
    - variable: MYSQL_USER
      default: nextcloud
      label: MySQL User
      required: true
      type: string
    - variable: MYSQL_PASS
      label: MySQL Pass
      required: true
      type: password
    - variable: MYSQL_ROOT_PASS
      label: MySQL root password
      required: true
      type: password
    - variable: LETSENCRYPT_EMAIL
      label: LetsEncrypt Email
      required: true
      type: string
    - variable: VIRTUAL_HOST
      label: Virtual Host
      required: true
      type: string      
services:

  db:
    scale: 1
    start_on_create: true

  nextcloud:
    scale: 1
    start_on_create: true

  proxy:
    scale: 1
    start_on_create: true

  letsencrypt-companion:
    scale: 1
    start_on_create: true


